# Base configs
#baseurl: "https://dbdhuri.github.io/poojadhuri.github.io/"
baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
#google_analytics: "UA-46465113-2"

# UI configs
title: "Art by Pooja D Dhuri"
subtitle: ""
author: "Pooja Dattaraj Dhuri"
header:
 title: "Art"
 subtitle: "by Pooja D Dhuri"
footer:
 name: "Hi, I am Pooja Dhuri"
 bio: "I am a visual artist from Mumbai, India. This is a selection of my artworks. Feel free to get in touch to know more."
 github: ""
web_design: "AJ, Ram Patra"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
# exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  instagram: "https://www.instagram.com/poojatilve/"
  linkedin: "https://www.linkedin.com/in/pooja-tilve-2b293258/"
  
